version: '3'

# Creación de volúmenes para almacenar los datos de ambos servicios de manera persistente.

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

# Comienzo a crear las bases de los servicios

services:
  prometheus:
    image: prom/prometheus:latest # Se empleará la última versión de la imagen de Prometheus.
    container_name: prometheus_serviem # Lo nombro con el nombre de la empresa.
    ports:
    - "9090:9090" # El servicio se ejecutará en los puertos 9090:9090
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
      # Se crean estos volúmenes para tener un archivo de configuración donde ajustar
      # los objetivos con los que Prometheus debe establecer conexión y recopilar las métricas.
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_serviem
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /path/to/data:/config
        environment:
            - TZ=
            - PGID=
            - PUID=
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
